---
- name: Install and run nginx, filebeat, auditbeat on server log
  hosts: web
  become: True
  gather_facts: false
  tasks:
    - name: Add repository Filebeat on web
      ansible.builtin.yum_repository:
        name: elastic.repo
        description: Elastic repo
        baseurl: https://artifacts.elastic.co/packages/7.x/yum
        gpgcheck: yes 
        gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        enabled: yes

    - name: Install nginx on web
      yum:  
        name: "nginx"
        state: present

    - name: Install filebeat on web
      yum:  
        name: "filebeat"
        state: present

    - name: Install auditbeat on web
      yum:  
        name: "auditbeat"
        state: present

    - name: Template a file configuration for filebeat
      template: 
        src: templates/filebeat.yml.j2
        dest: /etc/filebeat/filebeat.yml

    - name: Template a file configuration for auditbeat
      template: 
        src: templates/auditbeat.yml.j2
        dest: /etc/auditbeat/auditbeat.yml
        
    - name: Start filebeat
      systemd:
        state: started
        name: filebeat

    - name: Start auditbeat
      systemd:
        state: started
        name: auditbeat

    - name: Start nginx
      systemd:
        state: started
        name: nginx        

- name: Install and run logstash, elasticsearch and kibana on server log
  hosts: log
  become: true
  gather_facts: false
  tasks:
    - name: Add repository Filebeat on web
      ansible.builtin.yum_repository:
        name: elastic.repo
        description: Elastic repo
        baseurl: https://artifacts.elastic.co/packages/7.x/yum
        gpgcheck: yes 
        gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        enabled: yes

    - name: Install logstash on log
      yum:  
        name: "logstash"
        state: present

    - name: Install elasticsearch on log
      yum:  
        name: "elasticsearch"
        state: present

    - name: Install kibana on log
      yum:  
        name: "kibana"
        state: present

    - name: Install net-tools for add route on log
      yum:
        name: "net-tools"
        state: present

    - name: Template a file configuration for logstash
      template: 
        src: templates/10-pipeline.conf.j2
        dest: /etc/logstash/conf.d/10-pipeline.conf

    - name: Template a file configuration for elasticsearch
      template: 
        src: templates/elasticsearch.yml.j2
        dest: /etc/elasticsearch/elasticsearch.yml

    - name: Template a file configuration for kibana
      template: 
        src: templates/kibana.yml.j2
        dest: /etc/kibana/kibana.yml

    - name: Start logstash
      systemd:
        state: started
        name: logstash

    - name: Start elasticsearch
      systemd:
        state: started
        name: elasticsearch

    - name: Start kibana
      systemd:
        state: started
        name: kibana

    - name: Make default route from server log to notebook
      command: route add default gw 192.168.56.1
    
    - name: Disable firewalld on web
      systemd:
        state: stopped
        name: firewalld

    - name: Disable firewalld on log
      systemd:
        state: stopped
        name: firewalld

    